#!/bin/bash
apt-get install git curl wget proxychains python vim
git clone https://github.com/ssrbackup/shadowsocksr /usr/local/ssr
chmod -R 777 /usr/local/ssr
wget "http://120.77.144.164/ssr.json" -O /etc/ssr.json
chmod 777 /etc/ssr.json
wget 'https://raw.githubusercontent.com/10375951137/ssr/master/autoproxy.pac' -O /home/autoproxy.pac
echo 'export ALL_PROXY=socks5://127.0.0.1:1080'> ~/.bashrc
wget 'https://raw.githubusercontent.com/10375951137/ssr/master/start.sh' -O /usr/bin/ssr
chmod 777 /usr/bin/ssr
echo -e "\n\n在系统设置>网络>网络代理>自动>填入 file://home/autoproxy.pac\n\n"
exit 0

